name: Build and Test Docker Package on Staging

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository and build
        id: checkout_repository
        uses: actions/checkout@v4
        run: |
          APP_VERSION=$(grep -Po 'version="\K[^\"]+' src/main.py)
          docker build -t mymi14s/pexels-apis-explorer:$APP_VERSION .
          docker build -t mymi14s/pexels-apis-explorer:latest .
          docker run -d --name pexels-explorer -p8000:8000 mymi14s/pexels-apis-explorer:latest
          if [ "$(docker container ps -q -f name=pexels-explorer)" ]; then
            echo "The container is running."
          else
            echo "The container is not running."
            exit 1
          fi

